#
# This source file is part of the Stanford Spezi Template Web Dashboard open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> .env
  reuseaction:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v2
  markdownlinkcheck:
    name: Markdown Link Check
    uses: StanfordBDHG/.github/.github/workflows/markdown-link-check.yml@v2
  eslint:
    name: ESLint
    uses: StanfordBDHG/.github/.github/workflows/eslint.yml@v2
    permissions:
      checks: write
  testandcoverage:
    name: Test and Coverage
    uses: StanfordBDHG/.github/.github/workflows/npm-test-and-coverage.yml@v2
  dockercomposetest:
    needs: setup-env
    name: Docker Compose & Test
    uses: StanfordBDHG/.github/.github/workflows/docker-compose-test.yml@v2
    with:
      dockerComposeFile: docker-compose-development.yml
      testscript: test.sh
